"""
Lesson 16 - Narratives

Narratives are human-readable History entries that help users and support staff
understand what happened, when it happened, and why.
"""

from intelligence.intelligence import Intelligence  # type: ignore


STATE_ADDRESS = "lesson16/narratives"
LOCATION_PROPERTY_KEY = "lesson16_narrative_ref"


class LocationNarrativesMicroservice(Intelligence):
    def __init__(self, botengine, parent):
        super().__init__(botengine, parent)

    def schedule_fired(self, botengine, schedule_id):
        self.create_or_update_demo_narrative(botengine, schedule_id=schedule_id)

    def initialize(self, botengine):
        # Keep initialize light; create/update on a schedule in real usage.
        return

    def create_or_update_demo_narrative(self, botengine, schedule_id=None):
        """
        Create a narrative if one doesn't exist; otherwise update it.
        Stores narrative ID/time in a location property for later updates.
        """
        ref = self.parent.get_location_property(botengine, LOCATION_PROPERTY_KEY) or {}
        narrative_id = ref.get("narrativeId")
        narrative_time = ref.get("narrativeTime")

        title = _("Lesson 16 demo narrative")
        description = _("This narrative was generated by schedule '{}'.").format(
            schedule_id or "UNKNOWN"
        )

        # Update an existing record if we have a reference.
        update_id = narrative_id if narrative_id else None
        update_time = narrative_time if narrative_time else None

        response = self.parent.narrate(
            botengine,
            title=title,
            description=description,
            priority=botengine.NARRATIVE_PRIORITY_INFO,
            icon="book-open",
            update_narrative_id=update_id,
            update_narrative_timestamp=update_time,
            microservice_identifier=self.__class__.__module__,
            to_user=True,
            to_admin=False,
        )

        # Location.narrate returns {"user": Narrative|None, "admin": Narrative|None}
        user_ref = response.get("user") if isinstance(response, dict) else None
        if user_ref is not None and hasattr(user_ref, "narrative_id"):
            narrative_id = getattr(user_ref, "narrative_id", None)
            narrative_time = getattr(user_ref, "narrative_time", None)

        self.parent.set_location_property(
            botengine,
            LOCATION_PROPERTY_KEY,
            {"narrativeId": narrative_id, "narrativeTime": narrative_time},
            track=False,
        )

        botengine.set_state(
            STATE_ADDRESS,
            {
                "scheduleId": schedule_id,
                "narrativeId": narrative_id,
                "narrativeTime": narrative_time,
                "title": title,
                "description": description,
            },
            overwrite=True,
        )

